source ~/.profile

HISTFILESIZE=999999
HISTSIZE=999999
export PS1="@:\W$ "
export BASH_SILENCE_DEPRECATION_WARNING=1
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export GOPATH=/home/mstyushin/workspace/go
export PATH=${PATH}:/home/mstyushin/opt/go/bin:${GOPATH}/bin

